name: Azure Static Web Apps CI/CD
# ----------------------
# Trigger Workflow
#-----------------------
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
#-----------------------
# Workflow Jobs
#-----------------------
jobs:
  #---------------------
  # ☁️ Stage 1 - SETUP
  #---------------------
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Verify Angular Version
        run: npx ng version
  #-----------------------------
  # ☁️ Stage 2 - TEST AND BUILD
  #-----------------------------
  test_build:
    name: Test and Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Build Angular app
        run: npm run build --if-present
      # Save build artifacts for next stage (deploy on azure)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/
  # ========================
  # ☁️ Stage 3 - Deploy
  # ========================
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Deploy to Azure Static Web Apps
    runs-on: ubuntu-latest
    needs: test_build   # depends on Stage 2
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MUD_0D776F703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "dist/capstone-frontend/browser" # App source code path
          api_location: ""
          output_location: ""
          skip_app_build: true
